packages:
  - infrastructure
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@sentry/cli'
  - browser-tabs-lock
  - bufferutil
  - core-js
  - esbuild
  - protobufjs
  - utf-8-validate
