// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ApikeySecretJwtTemplate {
    /**
     * Role of the secret JWT template
     */
    role?: pulumi.Input<string>;
}

export interface BranchDatabase {
    /**
     * Host
     */
    host?: pulumi.Input<string>;
    /**
     * Branch project ref
     */
    id?: pulumi.Input<string>;
    /**
     * JWT secret
     */
    jwtSecret?: pulumi.Input<string>;
    /**
     * Password
     */
    password?: pulumi.Input<string>;
    /**
     * Port
     */
    port?: pulumi.Input<number>;
    /**
     * Status
     */
    status?: pulumi.Input<string>;
    /**
     * User
     */
    user?: pulumi.Input<string>;
    /**
     * Postgres version
     */
    version?: pulumi.Input<string>;
}

