// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ApikeySecretJwtTemplate {
    /**
     * Role of the secret JWT template
     */
    role: string;
}

export interface BranchDatabase {
    /**
     * Host
     */
    host: string;
    /**
     * Branch project ref
     */
    id: string;
    /**
     * JWT secret
     */
    jwtSecret: string;
    /**
     * Password
     */
    password: string;
    /**
     * Port
     */
    port: number;
    /**
     * Status
     */
    status: string;
    /**
     * User
     */
    user: string;
    /**
     * Postgres version
     */
    version: string;
}

export interface GetApikeysSecretKey {
    /**
     * The secret API key value
     */
    apiKey: string;
    /**
     * Name of the secret key
     */
    name: string;
}

export interface GetBranchBranch {
    /**
     * Git branch
     */
    gitBranch: string;
    /**
     * Branch identifier
     */
    id: string;
    /**
     * Branch project ref
     */
    projectRef: string;
}

